- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: install essentials for APT
    apt:
      name: apt-transport-https,ca-certificates,curl,gnupg2,software-properties-common

  - name: install packages
    apt:
      pkg:
      - fonts-noto
      - fonts-ipafont
      - fonts-ipaexfont
      - fish
      - mosh
      - iperf3

  - name: set dpkg architecture
    set_fact:
      dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

  - apt_key:
      url: https://download.docker.com/linux/debian/gpg
      id: 0EBFCD88
  - name: add Docker apt repository
    apt_repository:
      repo: deb [arch={{ dpkg_arch }}] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
      filename: docker
  - name: install Docker
    apt:
      name: docker-ce,docker-ce-cli,containerd.io
      update_cache: yes

  - apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
  - name: add VSCode apt repository
    apt_repository:
      repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
      filename: vscode
  - name: install VSCode
    apt:
      name: code
      update_cache: yes

  - apt_key:
      url: https://www.charlesproxy.com/packages/apt/PublicKey
  - name: add Charles Proxy apt repository
    apt_repository:
      repo: deb https://www.charlesproxy.com/packages/apt/ charles-proxy main
      filename: charles
  - name: install charles-proxy
    apt:
      name: charles-proxy
      update_cache: yes

  - name: dpkg add architecture i386
    shell: dpkg --add-architecture i386
    changed_when: false
  - apt_key:
      url: https://dl.winehq.org/wine-builds/winehq.key
  - name: add WineHQ apt repository
    apt_repository:
      repo: deb https://dl.winehq.org/wine-builds/debian {{ ansible_lsb.codename }} main
      filename: winehq
  - name: install Wine
    apt:
      name: winehq-devel
      install_recommends: yes
      update_cache: yes
