- hosts: localhost
  connection: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: install essentials for APT
    apt:
      name: apt-transport-https,ca-certificates,curl,gnupg2,software-properties-common

  - name: install packages
    apt:
      name: fonts-noto,fish,mosh,iperf3

  - apt_key:
      url: https://download.docker.com/linux/debian/gpg
      id: 0EBFCD88
  - name: add Docker apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      filename: docker
  - name: install Docker
    apt:
      name: docker-ce,docker-ce-cli,containerd.io
      update_cache: yes

  - apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
  - name: add VSCode apt repository
    apt_repository:
      repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
      filename: vscode
  - name: install VSCode
    apt:
      name: code
      update_cache: yes

  - apt_key:
      url: https://www.charlesproxy.com/packages/apt/PublicKey
  - name: add Charles Proxy apt repository
    apt_repository:
      repo: deb https://www.charlesproxy.com/packages/apt/ charles-proxy main
      filename: charles
  - name: install charles-proxy
    apt:
      name: charles-proxy
      update_cache: yes
