# for Ansible 2.2 (Chrome OS 74 Crostini)
- hosts: localhost
  connection: local
  become: yes
  tasks:
  - apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367
  - name: add Ansible apt repository
    apt_repository:
      repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
      filename: ansible
  - name: update Ansible to latest
    apt:
      name: ansible
      state: latest
